name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change if your main branch is 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff black dvc[s3] pytest   # Add any other required libs

    - name: Run lint (Ruff and Black)
      run: |
        ruff check .
        black --check .

    - name: DVC Pull (if using DVC)
      run: |
        dvc pull

    - name: Run tests
      run: |
        pytest
