name: Experiment 7 CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install lint tools
        run: |
          pip install black ruff
      - name: Run Black
        run: black --check .
      - name: Run Ruff
        run: ruff check .

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install test dependencies
        run: |
          pip install pytest
          pip install -r requirements.txt
      - name: Run tests
        run: pytest

  build-and-dvc:
    name: Build & DVC Pipeline
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install dvc[s3]
          pip install -r requirements.txt
      - name: Pull DVC artifacts (data/models)
        run: dvc pull
      - name: Run DVC pipeline (build)
        run: dvc repro
